//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateWebConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateWebConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppSetting: {0} = {1}.
        /// </summary>
        internal static string WebConfigUpdateAppSetting {
            get {
                return ResourceManager.GetString("WebConfigUpdateAppSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectionStringConfigSource = {0}.
        /// </summary>
        internal static string WebConfigUpdateConnectionStringConfigSource {
            get {
                return ResourceManager.GetString("WebConfigUpdateConnectionStringConfigSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomErrorsMode = {0}.
        /// </summary>
        internal static string WebConfigUpdateCustomErrorsMode {
            get {
                return ResourceManager.GetString("WebConfigUpdateCustomErrorsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug = {0}.
        /// </summary>
        internal static string WebConfigUpdateDebug {
            get {
                return ResourceManager.GetString("WebConfigUpdateDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0}.
        /// </summary>
        internal static string WebConfigUpdateDocument {
            get {
                return ResourceManager.GetString("WebConfigUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Configuration file not found: {0}.
        /// </summary>
        internal static string WebConfigUpdateFileNotFound {
            get {
                return ResourceManager.GetString("WebConfigUpdateFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailHost = {0}.
        /// </summary>
        internal static string WebConfigUpdateMailHost {
            get {
                return ResourceManager.GetString("WebConfigUpdateMailHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailPassword = {0}.
        /// </summary>
        internal static string WebConfigUpdateMailPassword {
            get {
                return ResourceManager.GetString("WebConfigUpdateMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailUserName = {0}.
        /// </summary>
        internal static string WebConfigUpdateMailUserName {
            get {
                return ResourceManager.GetString("WebConfigUpdateMailUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PickupDirectoryLocation = {0}.
        /// </summary>
        internal static string WebConfigUpdatePickupDirectoryLocation {
            get {
                return ResourceManager.GetString("WebConfigUpdatePickupDirectoryLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update completed on {0} and written to {1}.
        /// </summary>
        internal static string WebConfigUpdateResult {
            get {
                return ResourceManager.GetString("WebConfigUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sessionState mode = {0}.
        /// </summary>
        internal static string WebConfigUpdateSessionStateMode {
            get {
                return ResourceManager.GetString("WebConfigUpdateSessionStateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmtpDeliveryMethod = {0}.
        /// </summary>
        internal static string WebConfigUpdateSmtpDeliveryMethod {
            get {
                return ResourceManager.GetString("WebConfigUpdateSmtpDeliveryMethod", resourceCulture);
            }
        }
    }
}
